server:
  port: 8081
  servlet:
    context-path: /Employee
spring:
  cloud:
    config:
        enabled: false
  application:
    name: employee-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost